"""agent findings

Revision ID: c6ca5e223c34
Revises: c2686a34b5cd
Create Date: 2026-10-06 15:43:47.400155
"""
from alembic import op
import sqlalchemy as sa


revision = 'c6ca5e223c34'
down_revision = 'c2686a34b5cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=80), nullable=True),
    sa.Column('author', sa.String(length=60), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('conclusion', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('references', sa.JSON(), nullable=False),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_findings_repo_id'), 'agent_findings', ['repo_id'], unique=False)
    op.create_index(op.f('ix_agent_findings_run_id'), 'agent_findings', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_findings_topic'), 'agent_findings', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_findings_topic'), table_name='agent_findings')
    op.drop_index(op.f('ix_agent_findings_run_id'), table_name='agent_findings')
    op.drop_index(op.f('ix_agent_findings_repo_id'), table_name='agent_findings')
    op.drop_table('agent_findings')
    # ### end Alembic commands ###